"""
stub_generator.py - Terraform Stub File Generator
===================================================
Generates draft Terraform module stubs based on existing module patterns.

SAFETY: ONLY runs when --generate-stub flag is explicitly passed.
        NEVER runs terraform apply, plan, or destroy.
        NEVER modifies existing Terraform files.
        Only creates NEW files in the --output directory.
"""

import logging
import os
from pathlib import Path
from typing import Optional, Dict, List

from jinja2 import Environment, FileSystemLoader, select_autoescape

from models import AzureResource, DiscoveryReport
from terraform_search import get_module_variables

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SAFETY_WARNING = """
# ===========================================================================
# SAFETY: This file was AUTO-GENERATED by azure-terraform-dr-discovery-tool.
# It is a DRAFT STUB only. Review all TODO values before use.
# NEVER run terraform apply without:
#   1. Reviewing all variable values
#   2. Running terraform plan and reviewing the output
#   3. Confirming that import commands have been executed if resource exists
# ===========================================================================
"""


# ---------------------------------------------------------------------------
# Stub generator
# ---------------------------------------------------------------------------

class StubGenerator:
    """
    Generates Terraform stub files for discovered Azure resources.

    Reads existing module patterns to infer variable names and
    generates commented, safe-to-review draft files.
    """

    def __init__(
        self,
        output_dir: str,
        module_root: str,
        templates_dir: Optional[str] = None,
    ):
        """
        Args:
            output_dir: Where to write generated stubs.
            module_root: Path to terraform-modules repo.
            templates_dir: Path to Jinja2 templates.
        """
        self.output_dir = Path(output_dir)
        self.module_root = Path(module_root)
        self.templates_dir = Path(templates_dir) if templates_dir else (
            Path(__file__).parent.parent / "templates"
        )
        self._jinja_env: Optional[Environment] = None

    def _get_env(self) -> Environment:
        if self._jinja_env is None:
            self._jinja_env = Environment(
                loader=FileSystemLoader(str(self.templates_dir)),
                autoescape=select_autoescape([]),
                trim_blocks=True,
                lstrip_blocks=True,
                keep_trailing_newline=True,
            )
        return self._jinja_env

    def _find_module_path(self, module_name: str) -> Optional[Path]:
        """Find a module directory by name in the module root."""
        candidate = self.module_root / module_name
        if candidate.is_dir():
            return candidate
        # Try case-insensitive search
        if self.module_root.exists():
            for item in self.module_root.iterdir():
                if item.is_dir() and item.name.lower() == module_name.lower():
                    return item
        return None

    def generate_ai_search_stub(
        self,
        resource: AzureResource,
        env_path: str = "edav/dev",
    ) -> Dict[str, str]:
        """
        Generate Terraform stub files for an Azure AI Search service.

        Creates:
        - <output_dir>/<env_path>/ai_search_service/main.tf
        - <output_dir>/<env_path>/ai_search_service/variables.tf

        Args:
            resource: Discovered AzureResource.
            env_path: Environment folder path (e.g. edav/dev).

        Returns:
            Dict mapping file path -> file content.
        """
        module_name = "ai_search_service"
        module_path = self._find_module_path(module_name)
        module_source = (
            f"../../../../terraform-modules/{module_name}"
            if module_path
            else f"# TODO: Update path to your module
    # ../../../../terraform-modules/{module_name}"
        )

        # Collect known values from resource
        pe_list = resource.private_endpoints
        first_pe = pe_list[0] if pe_list else None

        # Build context for template
        context = {
            "safety_warning": SAFETY_WARNING,
            "resource": resource,
            "module_name": module_name,
            "module_source": module_source,
            "env_path": env_path,
            "first_pe": first_pe,
            "module_path": str(module_path) if module_path else None,
            "module_variables": (
                get_module_variables(str(module_path)) if module_path else {}
            ),
        }

        # Generate files
        files = {}
        base_dir = self.output_dir / env_path / module_name

        for template_name, output_filename in [
            ("terraform_ai_search_main.tf.j2", "main.tf"),
            ("terraform_ai_search_variables.tf.j2", "variables.tf"),
        ]:
            output_path = base_dir / output_filename
            try:
                env = self._get_env()
                tmpl = env.get_template(template_name)
                content = tmpl.render(**context)
            except Exception as exc:
                logger.warning(
                    "Template %s failed: %s. Using fallback.", template_name, exc
                )
                if output_filename == "main.tf":
                    content = self._fallback_ai_search_main(resource, module_source, first_pe)
                else:
                    content = self._fallback_ai_search_variables(resource)

            files[str(output_path)] = content

        # Write files
        written = {}
        for file_path, content in files.items():
            path = Path(file_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            logger.info("Generated stub: %s", path)
            written[file_path] = content

        # Generate import commands file
        import_path = base_dir / "import_commands.sh"
        import_content = self._generate_import_commands(resource, module_name)
        import_path.write_text(import_content, encoding="utf-8")
        written[str(import_path)] = import_content

        return written

    def _fallback_ai_search_main(
        self,
        resource: AzureResource,
        module_source: str,
        pe: Optional[object],
    ) -> str:
        """Fallback main.tf generator if template is unavailable."""
        pe_name = pe.name if pe else "# TODO: private endpoint name"
        pe_vnet = pe.vnet_name if pe else "# TODO"
        pe_subnet = pe.subnet_name if pe else "# TODO"
        pe_ip = pe.private_ip_address if pe else "# TODO"

        lines = [
            SAFETY_WARNING,
            'locals {',
            '  # TODO: Update these values from your environment configuration',
            f'  resource_group_name = "{resource.resource_group}"',
            f'  location            = "{resource.location}"',
            '}',
            '',
            'module "ai_search_service" {',
            f'  source = "{module_source}"',
            '',
            f'  # Resource identity - confirmed from Azure',
            f'  name                = "{resource.name}"',
            f'  resource_group_name = local.resource_group_name',
            f'  location            = local.location',
            f'  sku                 = "{resource.sku_name or "# TODO: sku name"}"',
            '',
            '  # Network configuration',
            '  public_network_access_enabled = ' + (
                'false' if (resource.public_network_access or "").lower() == "disabled"
                else '# TODO: true or false'
            ),
            '',
            '  # Private endpoint configuration',
            f'  # PE Name:     {pe_name}',
            f'  # VNet:        {pe_vnet}',
            f'  # Subnet:      {pe_subnet}',
            f'  # Private IP:  {pe_ip}',
            '',
            '  # TODO: Identity - confirm managed identity type',
            f'  identity_type = "{resource.identity.type if resource.identity else "SystemAssigned"}"',
            '',
            '  # TODO: Log Analytics workspace ID',
            '  log_analytics_workspace_id = var.log_analytics_workspace_id',
            '',
            '  # TODO: Admin and developer group object IDs',
            '  admin_group_object_id     = var.admin_group_object_id',
            '  developer_group_object_id = var.developer_group_object_id',
            '',
            '  # Tags - confirmed from Azure',
        ]
        if resource.tags:
            lines.append('  tags = {')
            for k, v in resource.tags.items():
                lines.append(f'    {k} = "{v}"')
            lines.append('  }')
        else:
            lines.append('  tags = var.tags  # TODO: define tags')
        lines.append('}')
        return "\n".join(lines) + "\n"

    def _fallback_ai_search_variables(self, resource: AzureResource) -> str:
        """Fallback variables.tf generator if template is unavailable."""
        return SAFETY_WARNING + '\n'.join([
            'variable "log_analytics_workspace_id" {',
            '  description = "TODO: Log Analytics workspace resource ID for diagnostic settings"',
            '  type        = string',
            '}',
            '',
            'variable "admin_group_object_id" {',
            '  description = "TODO: Azure AD group object ID for admin access"',
            '  type        = string',
            '}',
            '',
            'variable "developer_group_object_id" {',
            '  description = "TODO: Azure AD group object ID for developer access"',
            '  type        = string',
            '}',
            '',
            'variable "tags" {',
            '  description = "TODO: Resource tags"',
            '  type        = map(string)',
            '  default     = {}',
            '}',
        ]) + "\n"

    def _generate_import_commands(
        self,
        resource: AzureResource,
        module_name: str,
    ) -> str:
        """Generate example terraform import commands (DO NOT run without review)."""
        lines = [
            "#!/bin/bash",
            "# ===========================================================================",
            "# IMPORT COMMANDS - DO NOT RUN WITHOUT REVIEW",
            "# These commands are examples only. Review before executing.",
            "# Run ONLY after: terraform init && terraform plan (no apply yet)",
            "# ===========================================================================",
            "",
            "# Step 1: Initialize Terraform",
            "# terraform init",
            "",
            "# Step 2: Preview the import (Terraform 1.5+)",
            "# terraform plan -generate-config-out=generated.tf",
            "",
            f"# Step 3: Import the existing Azure resource",
            f"# terraform import \\",
            f"#   'module.{module_name}.azurerm_search_service.this' \\",
            f"#   '{resource.resource_id}'",
            "",
            "# Step 4: Verify state after import",
            "# terraform show",
            "",
            "# Step 5: Run plan to check for drift",
            "# terraform plan",
            "",
            "# NOTE: DO NOT run terraform apply until plan output is reviewed",
            "# and approved by the resource owner.",
        ]
        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate_stub(
    service: str,
    report: DiscoveryReport,
    output_dir: str,
    module_root: str,
    templates_dir: Optional[str] = None,
    env_path: str = "edav/dev",
) -> List[str]:
    """
    Generate Terraform stub files for resources in the discovery report.

    Args:
        service: Service type (ai_search, openai, etc.).
        report: Populated DiscoveryReport.
        output_dir: Where to write generated stubs.
        module_root: Path to terraform-modules repo.
        templates_dir: Optional path to Jinja2 templates.
        env_path: Environment path for stub placement.

    Returns:
        List of generated file paths.
    """
    logger.info(
        "[STUB GENERATOR] Generating stubs for %d resource(s) in %s",
        len(report.azure_resources),
        output_dir,
    )
    gen = StubGenerator(
        output_dir=output_dir,
        module_root=module_root,
        templates_dir=templates_dir,
    )

    all_generated = []
    for resource in report.azure_resources:
        try:
            if service == "ai_search":
                written = gen.generate_ai_search_stub(resource, env_path)
            else:
                logger.warning(
                    "Stub generation not yet implemented for service: %s", service
                )
                continue
            all_generated.extend(written.keys())
        except Exception as exc:
            logger.error(
                "Stub generation failed for %s: %s", resource.name, exc
            )

    return all_generated
